SRCS+=	${SRCDIR}/conn.c	\
	${SRCDIR}/msgqueue.c	\
	${SRCDIR}/netmsg.c	\
	${SRCDIR}/buffer.c	\
	${SRCDIR}/log.c		\
	${SRCDIR}/scan.l	\
	${SRCDIR}/parse.y	\
	test.c

TESTUSER=	root

.include <bsd.prog.mk>
